import SwiftUI



struct AppConstants {
    static let defultAppCurrency = "USD"
    static let onboardingItems = [
        OnboardingItem(
            title: AppStrings.Onboarding.title1,
            description: AppStrings.Onboarding.desc1,
            image: .onboarding1
        ),
        OnboardingItem(
            title: AppStrings.Onboarding.title2,
            description: AppStrings.Onboarding.desc2,
            image: .onboarding2
        ),
        OnboardingItem(
            title: AppStrings.Onboarding.title3,
            description: AppStrings.Onboarding.desc3,
            image: .onboarding3
        )
    ]
   
    static let allCurrencies: [CurrencyItem] = [
        CurrencyItem(code: "AGLD", name: "AGLD", flag: "ⒶⒼ"),
        CurrencyItem(code: "FJD", name: "Fijian Dollar", flag: "🇫🇯"),
        CurrencyItem(code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨"),
        CurrencyItem(code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧"),
        CurrencyItem(code: "HNL", name: "Honduran Lempira", flag: "🇭🇳"),
        CurrencyItem(code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬"),
        CurrencyItem(code: "COSMOSDYDX", name: "COSMOSDYDX", flag: "ⒸⓄ"),
        CurrencyItem(code: "NEAR", name: "NEAR", flag: "ⓃⒺ"),
        CurrencyItem(code: "AIOZ", name: "AIOZ", flag: "ⒶⒾ"),
        CurrencyItem(code: "AUDIO", name: "AUDIO", flag: "ⒶⓊ"),
        CurrencyItem(code: "WLD", name: "WLD", flag: "ⓌⓁ"),
        CurrencyItem(code: "HNT", name: "HNT", flag: "ⒽⓃ"),
        CurrencyItem(code: "ETHFI", name: "ETHFI", flag: "ⒺⓉ"),
        CurrencyItem(code: "FARM", name: "FARM", flag: "ⒻⒶ"),
        CurrencyItem(code: "A8", name: "A8", flag: "Ⓐ"),
        CurrencyItem(code: "SDG", name: "Sudanese Pound", flag: "🇸🇩"),
        CurrencyItem(code: "DGB", name: "DGB", flag: "ⒹⒼ"),
        CurrencyItem(code: "AB", name: "AB", flag: "ⒶⒷ"),
        CurrencyItem(code: "BCH", name: "BCH", flag: "ⒷⒸ"),
        CurrencyItem(code: "AI", name: "AI", flag: "ⒶⒾ"),
        CurrencyItem(code: "FKP", name: "Falkland Islands Pound", flag: "🇫🇰"),
        CurrencyItem(code: "JST", name: "JST", flag: "ⒿⓈ"),
        CurrencyItem(code: "HOT", name: "HOT", flag: "ⒽⓄ"),
        CurrencyItem(code: "AO", name: "AO", flag: "ⒶⓄ"),
        CurrencyItem(code: "AR", name: "AR", flag: "ⒶⓇ"),
        CurrencyItem(code: "B3", name: "B3", flag: "Ⓑ"),
        CurrencyItem(code: "CHILLGUY", name: "CHILLGUY", flag: "ⒸⒽ"),
        CurrencyItem(code: "SEI", name: "SEI", flag: "ⓈⒺ"),
        CurrencyItem(code: "SEK", name: "Swedish Krona", flag: "🇸🇪"),
        CurrencyItem(code: "LION", name: "LION", flag: "ⓁⒾ"),
        CurrencyItem(code: "BB", name: "BB", flag: "ⒷⒷ"),
        CurrencyItem(code: "QAR", name: "Qatari Riyal", flag: "🇶🇦"),
        CurrencyItem(code: "JTO", name: "JTO", flag: "ⒿⓉ"),
        CurrencyItem(code: "WEMIX", name: "WEMIX", flag: "ⓌⒺ"),
        CurrencyItem(code: "G", name: "G", flag: "ⒼⒼ"),
        CurrencyItem(code: "PROMPT", name: "PROMPT", flag: "ⓅⓇ"),
        CurrencyItem(code: "DHN", name: "DHN", flag: "ⒹⒽ"),
        CurrencyItem(code: "RLUSD", name: "Ripple USD", flag: "💵"),
        CurrencyItem(code: "FLR", name: "FLR", flag: "ⒻⓁ"),
        CurrencyItem(code: "O", name: "O", flag: "ⓄⓄ"),
        CurrencyItem(code: "BIGTIME", name: "BIGTIME", flag: "ⒷⒾ"),
        CurrencyItem(code: "S", name: "S", flag: "ⓈⓈ"),
        CurrencyItem(code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩"),
        CurrencyItem(code: "T", name: "T", flag: "ⓉⓉ"),
        CurrencyItem(code: "LYD", name: "Libyan Dinar", flag: "🇱🇾"),
        CurrencyItem(code: "W", name: "W", flag: "ⓌⓌ"),
        CurrencyItem(code: "BDX", name: "BDX", flag: "ⒷⒹ"),
        CurrencyItem(code: "BABYDOGE", name: "Baby Doge Coin", flag: "💵"),
        CurrencyItem(code: "SFP", name: "SFP", flag: "ⓈⒻ"),
        CurrencyItem(code: "DIA", name: "DIA", flag: "ⒹⒾ"),
        CurrencyItem(code: "PORK", name: "PORK", flag: "ⓅⓄ"),
        CurrencyItem(code: "JUP", name: "JUP", flag: "ⒿⓊ"),
        CurrencyItem(code: "RSS3", name: "RSS3", flag: "ⓇⓈ"),
        CurrencyItem(code: "SNEK", name: "SNEK", flag: "ⓈⓃ"),
        CurrencyItem(code: "LYX", name: "LYX", flag: "ⓁⓎ"),
        CurrencyItem(code: "SGB", name: "SGB", flag: "ⓈⒼ"),
        CurrencyItem(code: "SGD", name: "Singapore Dollar", flag: "🇸🇬"),
        CurrencyItem(code: "STRD", name: "STRD", flag: "ⓈⓉ"),
        CurrencyItem(code: "WOO", name: "WOO", flag: "ⓌⓄ"),
        CurrencyItem(code: "BLUR", name: "BLUR", flag: "ⒷⓁ"),
        CurrencyItem(code: "STRK", name: "STRK", flag: "ⓈⓉ"),
        CurrencyItem(code: "HRK", name: "Croatian Kuna", flag: "🇭🇷"),
        CurrencyItem(code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯"),
        CurrencyItem(code: "OMIKAMI", name: "OMIKAMI", flag: "ⓄⓂ"),
        CurrencyItem(code: "WAVES", name: "WAVES", flag: "ⓌⒶ"),
        CurrencyItem(code: "DOGINME", name: "DOGINME", flag: "ⒹⓄ"),
        CurrencyItem(code: "FLOKI", name: "Floki", flag: "💵"),
        CurrencyItem(code: "SHP", name: "Saint Helena Pound", flag: "🇸🇭"),
        CurrencyItem(code: "BGB", name: "BGB", flag: "ⒷⒼ"),
        CurrencyItem(code: "STEAKUSDC", name: "STEAKUSDC", flag: "ⓈⓉ"),
        CurrencyItem(code: "SAND", name: "SAND", flag: "ⓈⒶ"),
        CurrencyItem(code: "DKK", name: "Danish Krone", flag: "🇩🇰"),
        CurrencyItem(code: "AVNT", name: "AVNT", flag: "ⒶⓋ"),
        CurrencyItem(code: "WCFG", name: "WCFG", flag: "ⓌⒸ"),
        CurrencyItem(code: "QUBIC", name: "QUBIC", flag: "ⓆⓊ"),
        CurrencyItem(code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬"),
        CurrencyItem(code: "UMA", name: "UMA", flag: "ⓊⓂ"),
        CurrencyItem(code: "FOX", name: "FOX", flag: "ⒻⓄ"),
        CurrencyItem(code: "WSTETH", name: "Wrapped stETH", flag: "Ξ"),
        CurrencyItem(code: "TUSD", name: "TrueUSD", flag: "💵"),
        CurrencyItem(code: "LRDS", name: "LRDS", flag: "ⓁⓇ"),
        CurrencyItem(code: "COOKIE", name: "COOKIE", flag: "ⒸⓄ"),
        CurrencyItem(code: "HTG", name: "Haitian Gourde", flag: "🇭🇹"),
        CurrencyItem(code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭"),
        CurrencyItem(code: "PUNDIAI", name: "PUNDIAI", flag: "ⓅⓊ"),
        CurrencyItem(code: "OAS", name: "OAS", flag: "ⓄⒶ"),
        CurrencyItem(code: "PEAQ", name: "PEAQ", flag: "ⓅⒺ"),
        CurrencyItem(code: "COVAL", name: "COVAL", flag: "ⒸⓄ"),
        CurrencyItem(code: "ZETACHAIN", name: "ZETACHAIN", flag: "ⓏⒺ"),
        CurrencyItem(code: "CGLD", name: "CGLD", flag: "ⒸⒼ"),
        CurrencyItem(code: "MYRO", name: "MYRO", flag: "ⓂⓎ"),
        CurrencyItem(code: "UNI", name: "UNI", flag: "ⓊⓃ"),
        CurrencyItem(code: "QFI", name: "QFI", flag: "ⓆⒻ"),
        CurrencyItem(code: "HUF", name: "Hungarian Forint", flag: "🇭🇺"),
        CurrencyItem(code: "METAKPK", name: "METAKPK", flag: "ⓂⒺ"),
        CurrencyItem(code: "BIF", name: "Burundian Franc", flag: "🇧🇮"),
        CurrencyItem(code: "JUPITER", name: "JUPITER", flag: "ⒿⓊ"),
        CurrencyItem(code: "PEPECOIN", name: "Pepecoin", flag: "💵"),
        CurrencyItem(code: "WHITE", name: "WHITE", flag: "ⓌⒽ"),
        CurrencyItem(code: "WELL", name: "WELL", flag: "ⓌⒺ"),
        CurrencyItem(code: "BIO", name: "BIO", flag: "ⒷⒾ"),
        CurrencyItem(code: "SWFTC", name: "SWFTC", flag: "ⓈⓌ"),
        CurrencyItem(code: "WAVAX", name: "WAVAX", flag: "ⓌⒶ"),
        CurrencyItem(code: "BIT", name: "BIT", flag: "ⒷⒾ"),
        CurrencyItem(code: "GT", name: "GT", flag: "ⒼⓉ"),
        CurrencyItem(code: "SKL", name: "SKL", flag: "ⓈⓀ"),
        CurrencyItem(code: "UOS", name: "UOS", flag: "ⓊⓄ"),
        CurrencyItem(code: "WST", name: "WST", flag: "ⓌⓈ"),
        CurrencyItem(code: "SHPING", name: "SHPING", flag: "ⓈⒽ"),
        CurrencyItem(code: "SKR", name: "SKR", flag: "ⓈⓀ"),
        CurrencyItem(code: "BRETT", name: "Brett", flag: "💵"),
        CurrencyItem(code: "SKY", name: "SKY", flag: "ⓈⓀ"),
        CurrencyItem(code: "MYTH", name: "MYTH", flag: "ⓂⓎ"),
        CurrencyItem(code: "DNT", name: "DNT", flag: "ⒹⓃ"),
        CurrencyItem(code: "HT", name: "HT", flag: "ⒽⓉ"),
        CurrencyItem(code: "SLE", name: "Sierra Leonean Leone", flag: "🇸🇱"),
        CurrencyItem(code: "FLOW", name: "FLOW", flag: "ⒻⓁ"),
        CurrencyItem(code: "SLL", name: "Sierra Leonean Leone (old)", flag: "🇸🇱"),
        CurrencyItem(code: "SLP", name: "SLP", flag: "ⓈⓁ"),
        CurrencyItem(code: "ID", name: "ID", flag: "ⒾⒹ"),
        CurrencyItem(code: "DOG", name: "Dog (Bitcoin)", flag: "💵"),
        CurrencyItem(code: "GIGA", name: "GIGA", flag: "ⒼⒾ"),
        CurrencyItem(code: "DOP", name: "DOP", flag: "ⒹⓄ"),
        CurrencyItem(code: "IO", name: "IO", flag: "ⒾⓄ"),
        CurrencyItem(code: "UQC", name: "UQC", flag: "ⓊⓆ"),
        CurrencyItem(code: "IP", name: "IP", flag: "ⒾⓅ"),
        CurrencyItem(code: "IQ", name: "IQ", flag: "ⒾⓆ"),
        CurrencyItem(code: "DOT", name: "DOT", flag: "ⒹⓄ"),
        CurrencyItem(code: "OSAK", name: "OSAK", flag: "ⓄⓈ"),
        CurrencyItem(code: "1INCH", name: "1INCH", flag: "Ⓘ"),
        CurrencyItem(code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦"),
        CurrencyItem(code: "XSGD", name: "Tokenized Singapore Dollar", flag: "🇸🇬"),
        CurrencyItem(code: "TURBO", name: "TURBO", flag: "ⓉⓊ"),
        CurrencyItem(code: "BLD", name: "BLD", flag: "ⒷⓁ"),
        CurrencyItem(code: "UNFI", name: "UNFI", flag: "ⓊⓃ"),
        CurrencyItem(code: "APEX", name: "APEX", flag: "ⒶⓅ"),
        CurrencyItem(code: "FTM", name: "FTM", flag: "ⒻⓉ"),
        CurrencyItem(code: "EVER", name: "EVER", flag: "ⒺⓋ"),
        CurrencyItem(code: "POWR", name: "POWR", flag: "ⓅⓄ"),
        CurrencyItem(code: "MAV", name: "MAV", flag: "ⓂⒶ"),
        CurrencyItem(code: "CORGIAI", name: "CORGIAI", flag: "ⒸⓄ"),
        CurrencyItem(code: "FTW", name: "FTW", flag: "ⒻⓉ"),
        CurrencyItem(code: "ARKM", name: "ARKM", flag: "ⒶⓇ"),
        CurrencyItem(code: "ATOM", name: "ATOM", flag: "ⒶⓉ"),
        CurrencyItem(code: "SAVAX", name: "SAVAX", flag: "ⓈⒶ"),
        CurrencyItem(code: "QUICK", name: "QUICK", flag: "ⓆⓊ"),
        CurrencyItem(code: "PENDLE", name: "PENDLE", flag: "ⓅⒺ"),
        CurrencyItem(code: "BLZ", name: "BLZ", flag: "ⒷⓁ"),
        CurrencyItem(code: "BOBA", name: "BOBA", flag: "ⒷⓄ"),
        CurrencyItem(code: "TONE", name: "TONE", flag: "ⓉⓄ"),
        CurrencyItem(code: "BMD", name: "BMD", flag: "ⒷⓂ"),
        CurrencyItem(code: "SNT", name: "SNT", flag: "ⓈⓃ"),
        CurrencyItem(code: "SNX", name: "SNX", flag: "ⓈⓃ"),
        CurrencyItem(code: "KOGE", name: "KOGE", flag: "ⓀⓄ"),
        CurrencyItem(code: "SHIRO", name: "SHIRO", flag: "ⓈⒽ"),
        CurrencyItem(code: "L3", name: "L3", flag: "Ⓛ"),
        CurrencyItem(code: "USD", name: "US Dollar", flag: "🇺🇸"),
        CurrencyItem(code: "API3", name: "API3", flag: "ⒶⓅ"),
        CurrencyItem(code: "ROSE", name: "ROSE", flag: "ⓇⓄ"),
        CurrencyItem(code: "SATS", name: "SATS", flag: "ⓈⒶ"),
        CurrencyItem(code: "PORTAL", name: "PORTAL", flag: "ⓅⓄ"),
        CurrencyItem(code: "SOL", name: "SOL", flag: "ⓈⓄ"),
        CurrencyItem(code: "MUMU", name: "MUMU", flag: "ⓂⓊ"),
        CurrencyItem(code: "LA", name: "LA", flag: "ⓁⒶ"),
        CurrencyItem(code: "USR", name: "USR", flag: "ⓊⓈ"),
        CurrencyItem(code: "SOS", name: "SOS", flag: "ⓈⓄ"),
        CurrencyItem(code: "BNB", name: "BNB", flag: "ⒷⓃ"),
        CurrencyItem(code: "OGN", name: "OGN", flag: "ⓄⒼ"),
        CurrencyItem(code: "UST", name: "TerraUSD (old)", flag: "💵"),
        CurrencyItem(code: "CELR", name: "CELR", flag: "ⒸⒺ"),
        CurrencyItem(code: "CGPT", name: "CGPT", flag: "ⒸⒼ"),
        CurrencyItem(code: "BND", name: "Brunei Dollar", flag: "🇧🇳"),
        CurrencyItem(code: "CELO", name: "CELO", flag: "ⒸⒺ"),
        CurrencyItem(code: "TBTC", name: "tBTC", flag: "₿"),
        CurrencyItem(code: "NOICE", name: "NOICE", flag: "ⓃⓄ"),
        CurrencyItem(code: "AUCTION", name: "AUCTION", flag: "ⒶⓊ"),
        CurrencyItem(code: "LAYER", name: "LAYER", flag: "ⓁⒶ"),
        CurrencyItem(code: "MANTA", name: "MANTA", flag: "ⓂⒶ"),
        CurrencyItem(code: "BADGER", name: "BADGER", flag: "ⒷⒶ"),
        CurrencyItem(code: "MULTI", name: "MULTI", flag: "ⓂⓊ"),
        CurrencyItem(code: "AERO", name: "AERO", flag: "ⒶⒺ"),
        CurrencyItem(code: "CETUS", name: "CETUS", flag: "ⒸⒺ"),
        CurrencyItem(code: "SPA", name: "SPA", flag: "ⓈⓅ"),
        CurrencyItem(code: "BNT", name: "BNT", flag: "ⒷⓃ"),
        CurrencyItem(code: "DRV", name: "DRV", flag: "ⒹⓇ"),
        CurrencyItem(code: "SHDW", name: "SHDW", flag: "ⓈⒽ"),
        CurrencyItem(code: "SPK", name: "SPK", flag: "ⓈⓅ"),
        CurrencyItem(code: "FLOCK", name: "FLOCK", flag: "ⒻⓁ"),
        CurrencyItem(code: "BOB", name: "BOB", flag: "ⒷⓄ"),
        CurrencyItem(code: "MDL", name: "Moldovan Leu", flag: "🇲🇩"),
        CurrencyItem(code: "OHM", name: "OHM", flag: "ⓄⒽ"),
        CurrencyItem(code: "ME", name: "ME", flag: "ⓂⒺ"),
        CurrencyItem(code: "SPX", name: "SPX", flag: "ⓈⓅ"),
        CurrencyItem(code: "MDT", name: "MDT", flag: "ⓂⒹ"),
        CurrencyItem(code: "ANDY", name: "ANDY", flag: "ⒶⓃ"),
        CurrencyItem(code: "AERGO", name: "AERGO", flag: "ⒶⒺ"),
        CurrencyItem(code: "MOCA", name: "MOCA", flag: "ⓂⓄ"),
        CurrencyItem(code: "SQD", name: "SQD", flag: "ⓈⓆ"),
        CurrencyItem(code: "MX", name: "MX", flag: "ⓂⓍ"),
        CurrencyItem(code: "EGLD", name: "EGLD", flag: "ⒺⒼ"),
        CurrencyItem(code: "PLUME", name: "PLUME", flag: "ⓅⓁ"),
        CurrencyItem(code: "KAS", name: "KAS", flag: "ⓀⒶ"),
        CurrencyItem(code: "TRUMP", name: "TRUMP", flag: "ⓉⓇ"),
        CurrencyItem(code: "MET", name: "MET", flag: "ⓂⒺ"),
        CurrencyItem(code: "MEW", name: "MEW", flag: "ⓂⒺ"),
        CurrencyItem(code: "KAT", name: "KAT", flag: "ⓀⒶ"),
        CurrencyItem(code: "PUNDIX", name: "PUNDIX", flag: "ⓅⓊ"),
        CurrencyItem(code: "AEVO", name: "AEVO", flag: "ⒶⒺ"),
        CurrencyItem(code: "DADDYCHILL", name: "DADDYCHILL", flag: "ⒹⒶ"),
        CurrencyItem(code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷"),
        CurrencyItem(code: "PTGC", name: "PTGC", flag: "ⓅⓉ"),
        CurrencyItem(code: "NU", name: "NU", flag: "ⓃⓊ"),
        CurrencyItem(code: "FLUX", name: "FLUX", flag: "ⒻⓁ"),
        CurrencyItem(code: "TOPIA", name: "TOPIA", flag: "ⓉⓄ"),
        CurrencyItem(code: "BPX", name: "BPX", flag: "ⒷⓅ"),
        CurrencyItem(code: "PRCL", name: "PRCL", flag: "ⓅⓇ"),
        CurrencyItem(code: "WRON", name: "WRON", flag: "ⓌⓇ"),
        CurrencyItem(code: "QNT", name: "QNT", flag: "ⓆⓃ"),
        CurrencyItem(code: "EDGEX", name: "EDGEX", flag: "ⒺⒹ"),
        CurrencyItem(code: "MUSD", name: "mUSD", flag: "💵"),
        CurrencyItem(code: "ETHW", name: "EthereumPoW", flag: "Ξ"),
        CurrencyItem(code: "MUSE", name: "MUSE", flag: "ⓂⓊ"),
        CurrencyItem(code: "ETHX", name: "ETHX", flag: "ⒺⓉ"),
        CurrencyItem(code: "OP", name: "OP", flag: "ⓄⓅ"),
        CurrencyItem(code: "CANTO", name: "CANTO", flag: "ⒸⒶ"),
        CurrencyItem(code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬"),
        CurrencyItem(code: "OKB", name: "OKB", flag: "ⓄⓀ"),
        CurrencyItem(code: "WETH", name: "Wrapped Ethereum", flag: "Ξ"),
        CurrencyItem(code: "SSP", name: "SSP", flag: "ⓈⓈ"),
        CurrencyItem(code: "JUPSOL", name: "JUPSOL", flag: "ⒿⓊ"),
        CurrencyItem(code: "NEON", name: "NEON", flag: "ⓃⒺ"),
        CurrencyItem(code: "MURA", name: "MURA", flag: "ⓂⓊ"),
        CurrencyItem(code: "SSV", name: "SSV", flag: "ⓈⓈ"),
        CurrencyItem(code: "PI", name: "PI", flag: "ⓅⒾ"),
        CurrencyItem(code: "ETH2", name: "Ethereum 2.0", flag: "Ξ"),
        CurrencyItem(code: "PAAL", name: "PAAL", flag: "ⓅⒶ"),
        CurrencyItem(code: "KCS", name: "KCS", flag: "ⓀⒸ"),
        CurrencyItem(code: "BUSD", name: "Binance USD", flag: "💵"),
        CurrencyItem(code: "ARPA", name: "ARPA", flag: "ⒶⓇ"),
        CurrencyItem(code: "BRL", name: "Brazilian Real", flag: "🇧🇷"),
        CurrencyItem(code: "ALCX", name: "ALCX", flag: "ⒶⓁ"),
        CurrencyItem(code: "ALEX", name: "ALEX", flag: "ⒶⓁ"),
        CurrencyItem(code: "STG", name: "STG", flag: "ⓈⓉ"),
        CurrencyItem(code: "IOTX", name: "IOTX", flag: "ⒾⓄ"),
        CurrencyItem(code: "SHIB", name: "Shiba Inu", flag: "💵"),
        CurrencyItem(code: "KDA", name: "KDA", flag: "ⓀⒹ"),
        CurrencyItem(code: "$MICHI", name: "$MICHI", flag: "ⓂⒾ"),
        CurrencyItem(code: "ZAR", name: "South African Rand", flag: "🇿🇦"),
        CurrencyItem(code: "ALEO", name: "ALEO", flag: "ⒶⓁ"),
        CurrencyItem(code: "STN", name: "Sao Tome and Principe Dobra", flag: "🇸🇹"),
        CurrencyItem(code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸"),
        CurrencyItem(code: "STX", name: "STX", flag: "ⓈⓉ"),
        CurrencyItem(code: "TROLL", name: "TROLL", flag: "ⓉⓇ"),
        CurrencyItem(code: "QI", name: "QI", flag: "ⓆⒾ"),
        CurrencyItem(code: "ZBC", name: "ZBC", flag: "ⓏⒷ"),
        CurrencyItem(code: "BLAST", name: "BLAST", flag: "ⒷⓁ"),
        CurrencyItem(code: "BSV", name: "BSV", flag: "ⒷⓈ"),
        CurrencyItem(code: "IOST", name: "IOST", flag: "ⒾⓄ"),
        CurrencyItem(code: "SUI", name: "SUI", flag: "ⓈⓊ"),
        CurrencyItem(code: "TGBP", name: "Tokenized British Pound", flag: "🇬🇧"),
        CurrencyItem(code: "CAKE", name: "CAKE", flag: "ⒸⒶ"),
        CurrencyItem(code: "MSOL", name: "MSOL", flag: "ⓂⓈ"),
        CurrencyItem(code: "OMG", name: "OMG", flag: "ⓄⓂ"),
        CurrencyItem(code: "OMI", name: "OMI", flag: "ⓄⓂ"),
        CurrencyItem(code: "PYUSD", name: "PayPal USD", flag: "💵"),
        CurrencyItem(code: "SUN", name: "SUN", flag: "ⓈⓊ"),
        CurrencyItem(code: "SUP", name: "SUP", flag: "ⓈⓊ"),
        CurrencyItem(code: "BTC", name: "Bitcoin", flag: "₿"),
        CurrencyItem(code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾"),
        CurrencyItem(code: "IOTA", name: "IOTA", flag: "ⒾⓄ"),
        CurrencyItem(code: "ZYPTO", name: "ZYPTO", flag: "ⓏⓎ"),
        CurrencyItem(code: "RE", name: "RE", flag: "ⓇⒺ"),
        CurrencyItem(code: "BTG", name: "BTG", flag: "ⒷⓉ"),
        CurrencyItem(code: "AIXBT", name: "AIXBT", flag: "ⒶⒾ"),
        CurrencyItem(code: "OMR", name: "Omani Rial", flag: "🇴🇲"),
        CurrencyItem(code: "MIR", name: "MIR", flag: "ⓂⒾ"),
        CurrencyItem(code: "KES", name: "Kenyan Shilling", flag: "🇰🇪"),
        CurrencyItem(code: "KET", name: "KET", flag: "ⓀⒺ"),
        CurrencyItem(code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹"),
        CurrencyItem(code: "RONIN", name: "RONIN", flag: "ⓇⓄ"),
        CurrencyItem(code: "SOLVBTC", name: "Solv BTC", flag: "₿"),
        CurrencyItem(code: "SVC", name: "Salvadoran Colon", flag: "🇸🇻"),
        CurrencyItem(code: "BTT", name: "BTT", flag: "ⒷⓉ"),
        CurrencyItem(code: "ONE", name: "ONE", flag: "ⓄⓃ"),
        CurrencyItem(code: "FWOG", name: "FWOG", flag: "ⒻⓌ"),
        CurrencyItem(code: "RENDER", name: "RENDER", flag: "ⓇⒺ"),
        CurrencyItem(code: "ONG", name: "ONG", flag: "ⓄⓃ"),
        CurrencyItem(code: "CETH", name: "CETH", flag: "ⒸⒺ"),
        CurrencyItem(code: "ANKR", name: "ANKR", flag: "ⒶⓃ"),
        CurrencyItem(code: "ALGO", name: "ALGO", flag: "ⒶⓁ"),
        CurrencyItem(code: "SYLO", name: "SYLO", flag: "ⓈⓎ"),
        CurrencyItem(code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿"),
        CurrencyItem(code: "SC", name: "SC", flag: "ⓈⒸ"),
        CurrencyItem(code: "SD", name: "SD", flag: "ⓈⒹ"),
        CurrencyItem(code: "ONT", name: "ONT", flag: "ⓄⓃ"),
        CurrencyItem(code: "FLUID", name: "FLUID", flag: "ⒻⓁ"),
        CurrencyItem(code: "DYM", name: "DYM", flag: "ⒹⓎ"),
        CurrencyItem(code: "DYP", name: "DYP", flag: "ⒹⓎ"),
        CurrencyItem(code: "WOULD", name: "WOULD", flag: "ⓌⓄ"),
        CurrencyItem(code: "MKD", name: "Macedonian Denar", flag: "🇲🇰"),
        CurrencyItem(code: "HYPER", name: "HYPER", flag: "ⒽⓎ"),
        CurrencyItem(code: "DZD", name: "Algerian Dinar", flag: "🇩🇿"),
        CurrencyItem(code: "WLFI", name: "WLFI", flag: "ⓌⓁ"),
        CurrencyItem(code: "MKR", name: "MKR", flag: "ⓂⓀ"),
        CurrencyItem(code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬"),
        CurrencyItem(code: "GRAM", name: "GRAM", flag: "ⒼⓇ"),
        CurrencyItem(code: "ICP", name: "ICP", flag: "ⒾⒸ"),
        CurrencyItem(code: "ZEC", name: "ZEC", flag: "ⓏⒺ"),
        CurrencyItem(code: "XAF", name: "Central African CFA Franc", flag: "🌍"),
        CurrencyItem(code: "ICX", name: "ICX", flag: "ⒾⒸ"),
        CurrencyItem(code: "XAG", name: "Silver Ounce", flag: "💵"),
        CurrencyItem(code: "KMNO", name: "KMNO", flag: "ⓀⓂ"),
        CurrencyItem(code: "XAI", name: "XAI", flag: "ⓍⒶ"),
        CurrencyItem(code: "ZEN", name: "ZEN", flag: "ⓏⒺ"),
        CurrencyItem(code: "XAN", name: "XAN", flag: "ⓍⒶ"),
        CurrencyItem(code: "FRIEND", name: "FRIEND", flag: "ⒻⓇ"),
        CurrencyItem(code: "OPG", name: "OPG", flag: "ⓄⓅ"),
        CurrencyItem(code: "DOGE", name: "Dogecoin", flag: "💵"),
        CurrencyItem(code: "SXP", name: "SXP", flag: "ⓈⓍ"),
        CurrencyItem(code: "HBAR", name: "HBAR", flag: "ⒽⒷ"),
        CurrencyItem(code: "OPN", name: "OPN", flag: "ⓄⓅ"),
        CurrencyItem(code: "XAU", name: "Gold Ounce", flag: "💵"),
        CurrencyItem(code: "MLN", name: "MLN", flag: "ⓂⓁ"),
        CurrencyItem(code: "SXT", name: "SXT", flag: "ⓈⓍ"),
        CurrencyItem(code: "PEPE", name: "Pepe", flag: "💵"),
        CurrencyItem(code: "FUN1", name: "FUN1", flag: "ⒻⓊ"),
        CurrencyItem(code: "KHR", name: "Cambodian Riel", flag: "🇰🇭"),
        CurrencyItem(code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩"),
        CurrencyItem(code: "DOGS", name: "Dogs", flag: "💵"),
        CurrencyItem(code: "CTSI", name: "CTSI", flag: "ⒸⓉ"),
        CurrencyItem(code: "BWP", name: "Botswanan Pula", flag: "🇧🇼"),
        CurrencyItem(code: "UP", name: "UP", flag: "ⓊⓅ"),
        CurrencyItem(code: "COMAI", name: "COMAI", flag: "ⒸⓄ"),
        CurrencyItem(code: "LINEA", name: "LINEA", flag: "ⓁⒾ"),
        CurrencyItem(code: "OUSG", name: "OUSG", flag: "ⓄⓊ"),
        CurrencyItem(code: "C98", name: "C98", flag: "Ⓒ"),
        CurrencyItem(code: "OSMO", name: "OSMO", flag: "ⓄⓈ"),
        CurrencyItem(code: "BASED1", name: "BASED1", flag: "ⒷⒶ"),
        CurrencyItem(code: "NTRN", name: "NTRN", flag: "ⓃⓉ"),
        CurrencyItem(code: "SYN", name: "SYN", flag: "ⓈⓎ"),
        CurrencyItem(code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲"),
        CurrencyItem(code: "SYP", name: "Syrian Pound", flag: "🇸🇾"),
        CurrencyItem(code: "CRPT", name: "CRPT", flag: "ⒸⓇ"),
        CurrencyItem(code: "SYBTC", name: "Synthetic BTC", flag: "₿"),
        CurrencyItem(code: "GAJ", name: "GAJ", flag: "ⒼⒶ"),
        CurrencyItem(code: "GAL", name: "GAL", flag: "ⒼⒶ"),
        CurrencyItem(code: "GAS", name: "GAS", flag: "ⒼⒶ"),
        CurrencyItem(code: "XCD", name: "East Caribbean Dollar", flag:"💵"),
        CurrencyItem(code: "MMX", name: "MMX", flag: "ⓂⓂ"),
        CurrencyItem(code: "BOME", name: "BOME", flag: "ⒷⓄ"),
        CurrencyItem(code: "SONIC", name: "SONIC", flag: "ⓈⓄ"),
        CurrencyItem(code: "SYND", name: "SYND", flag: "ⓈⓎ"),
        CurrencyItem(code: "VR", name: "VR", flag: "ⓋⓇ"),
        CurrencyItem(code: "XCH", name: "XCH", flag: "ⓍⒸ"),
        CurrencyItem(code: "XCG", name: "XCG", flag: "ⓍⒸ"),
        CurrencyItem(code: "CBBTC", name: "Coinbase Wrapped BTC", flag: "₿"),
        CurrencyItem(code: "ORA", name: "ORA", flag: "ⓄⓇ"),
        CurrencyItem(code: "THETA", name: "THETA", flag: "ⓉⒽ"),
        CurrencyItem(code: "PANDORA", name: "PANDORA", flag: "ⓅⒶ"),
        CurrencyItem(code: "XCN", name: "XCN", flag: "ⓍⒸ"),
        CurrencyItem(code: "SZL", name: "Swazi Lilangeni", flag: "🇸🇿"),
        CurrencyItem(code: "ORN", name: "ORN", flag: "ⓄⓇ"),
        CurrencyItem(code: "NEXO", name: "NEXO", flag: "ⓃⒺ"),
        CurrencyItem(code: "AAVE", name: "AAVE", flag: "ⒶⒶ"),
        CurrencyItem(code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳"),
        CurrencyItem(code: "GBP", name: "British Pound", flag: "🇬🇧"),
        CurrencyItem(code: "BONK", name: "Bonk", flag: "💵"),
        CurrencyItem(code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾"),
        CurrencyItem(code: "XDC", name: "XDC", flag: "ⓍⒹ"),
        CurrencyItem(code: "PERP", name: "PERP", flag: "ⓅⒺ"),
        CurrencyItem(code: "BONE", name: "BONE", flag: "ⒷⓄ"),
        CurrencyItem(code: "BOND", name: "BOND", flag: "ⒷⓄ"),
        CurrencyItem(code: "MOG", name: "MOG", flag: "ⓂⓄ"),
        CurrencyItem(code: "HYPE", name: "HYPE", flag: "ⒽⓎ"),
        CurrencyItem(code: "TIME", name: "TIME", flag: "ⓉⒾ"),
        CurrencyItem(code: "SAPIEN", name: "SAPIEN", flag: "ⓈⒶ"),
        CurrencyItem(code: "BICO", name: "BICO", flag: "ⒷⒾ"),
        CurrencyItem(code: "BZD", name: "BZD", flag: "ⒷⓏ"),
        CurrencyItem(code: "MON", name: "MON", flag: "ⓂⓄ"),
        CurrencyItem(code: "MOP", name: "Macanese Pataca", flag: "🇲🇴"),
        CurrencyItem(code: "ALLO", name: "ALLO", flag: "ⒶⓁ"),
        CurrencyItem(code: "NEWT", name: "NEWT", flag: "ⓃⒺ"),
        CurrencyItem(code: "MONA", name: "MONA", flag: "ⓂⓄ"),
        CurrencyItem(code: "BBSOL", name: "BBSOL", flag: "ⒷⒷ"),
        CurrencyItem(code: "MELANIA", name: "MELANIA", flag: "ⓂⒺ"),
        CurrencyItem(code: "HMSTR", name: "HMSTR", flag: "ⒽⓂ"),
        CurrencyItem(code: "XEC", name: "XEC", flag: "ⓍⒺ"),
        CurrencyItem(code: "PEOPLE", name: "PEOPLE", flag: "ⓅⒺ"),
        CurrencyItem(code: "BZR", name: "BZR", flag: "ⒷⓏ"),
        CurrencyItem(code: "XT", name: "XT", flag: "ⓍⓉ"),
        CurrencyItem(code: "ZIL", name: "ZIL", flag: "ⓏⒾ"),
        CurrencyItem(code: "TRUST", name: "TRUST", flag: "ⓉⓇ"),
        CurrencyItem(code: "XEM", name: "XEM", flag: "ⓍⒺ"),
        CurrencyItem(code: "WEETH", name: "Wrapped eETH", flag: "Ξ"),
        CurrencyItem(code: "TRAC", name: "TRAC", flag: "ⓉⓇ"),
        CurrencyItem(code: "YB", name: "YB", flag: "ⓎⒷ"),
        CurrencyItem(code: "10SET", name: "10SET", flag: "💵"),
        CurrencyItem(code: "GEOD", name: "GEOD", flag: "ⒼⒺ"),
        CurrencyItem(code: "WAXL", name: "WAXL", flag: "ⓌⒶ"),
        CurrencyItem(code: "OOKI", name: "OOKI", flag: "ⓄⓄ"),
        CurrencyItem(code: "SWELL", name: "SWELL", flag: "ⓈⓌ"),
        CurrencyItem(code: "BORA", name: "BORA", flag: "ⒷⓄ"),
        CurrencyItem(code: "KMF", name: "KMF", flag: "ⓀⓂ"),
        CurrencyItem(code: "GEL", name: "Georgian Lari", flag: "🇬🇪"),
        CurrencyItem(code: "ZK", name: "ZK", flag: "ⓏⓀ"),
        CurrencyItem(code: "RSETH", name: "KelpDAO ETH", flag: "Ξ"),
        CurrencyItem(code: "ZKC", name: "ZKC", flag: "ⓏⓀ"),
        CurrencyItem(code: "EETH", name: "ether.fi ETH", flag: "Ξ"),
        CurrencyItem(code: "USUAL", name: "USUAL", flag: "ⓊⓈ"),
        CurrencyItem(code: "KEKIUS", name: "KEKIUS", flag: "ⓀⒺ"),
        CurrencyItem(code: "ZKP", name: "ZKP", flag: "ⓏⓀ"),
        CurrencyItem(code: "KNC", name: "KNC", flag: "ⓀⓃ"),
        CurrencyItem(code: "PROS", name: "PROS", flag: "ⓅⓇ"),
        CurrencyItem(code: "PROM", name: "PROM", flag: "ⓅⓇ"),
        CurrencyItem(code: "ALEPH", name: "ALEPH", flag: "ⒶⓁ"),
        CurrencyItem(code: "PONKE", name: "PONKE", flag: "ⓅⓄ"),
        CurrencyItem(code: "BODEN", name: "BODEN", flag: "ⒷⓄ"),
        CurrencyItem(code: "GFI", name: "GFI", flag: "ⒼⒻ"),
        CurrencyItem(code: "MRS", name: "MRS", flag: "ⓂⓇ"),
        CurrencyItem(code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷"),
        CurrencyItem(code: "BORG", name: "BORG", flag: "ⒷⓄ"),
        CurrencyItem(code: "SUPEROETHB", name: "Super OETH", flag: "Ξ"),
        CurrencyItem(code: "WAXP", name: "WAXP", flag: "ⓌⒶ"),
        CurrencyItem(code: "SUKU", name: "SUKU", flag: "ⓈⓊ"),
        CurrencyItem(code: "DOLO", name: "DOLO", flag: "ⒹⓄ"),
        CurrencyItem(code: "SWARMS", name: "SWARMS", flag: "ⓈⓌ"),
        CurrencyItem(code: "GGP", name: "Guernsey Pound", flag: "🇬🇬"),
        CurrencyItem(code: "GRIN", name: "GRIN", flag: "ⒼⓇ"),
        CurrencyItem(code: "VEF", name: "VEF", flag: "ⓋⒺ"),
        CurrencyItem(code: "MTD", name: "MTD", flag: "ⓂⓉ"),
        CurrencyItem(code: "KARRAT", name: "KARRAT", flag: "ⓀⒶ"),
        CurrencyItem(code: "ALPH", name: "ALPH", flag: "ⒶⓁ"),
        CurrencyItem(code: "MOBILE", name: "MOBILE", flag: "ⓂⓄ"),
        CurrencyItem(code: "DOOD", name: "DOOD", flag: "ⒹⓄ"),
        CurrencyItem(code: "VINE", name: "VINE", flag: "ⓋⒾ"),
        CurrencyItem(code: "TAO", name: "TAO", flag: "ⓉⒶ"),
        CurrencyItem(code: "MORPHO", name: "MORPHO", flag: "ⓂⓄ"),
        CurrencyItem(code: "MTL", name: "MTL", flag: "ⓂⓉ"),
        CurrencyItem(code: "VET", name: "VET", flag: "ⓋⒺ"),
        CurrencyItem(code: "VES", name: "Venezuelan Bolivar", flag: "🇻🇪"),
        CurrencyItem(code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲"),
        CurrencyItem(code: "USDG", name: "Global Dollar", flag: "💵"),
        CurrencyItem(code: "LUCE", name: "LUCE", flag: "ⓁⓊ"),
        CurrencyItem(code: "AKUMA", name: "AKUMA", flag: "ⒶⓀ"),
        CurrencyItem(code: "USDT", name: "Tether", flag: "💵"),
        CurrencyItem(code: "USDC.E", name: "Bridged USDC", flag: "💵"),
        CurrencyItem(code: "OXT", name: "OXT", flag: "ⓄⓍ"),
        CurrencyItem(code: "USDS", name: "USDS", flag: "💵"),
        CurrencyItem(code: "USDP", name: "Pax Dollar", flag: "💵"),
        CurrencyItem(code: "GHO", name: "Aave GHO", flag: "💵"),
        CurrencyItem(code: "ILV", name: "ILV", flag: "ⒾⓁ"),
        CurrencyItem(code: "L1X", name: "L1X", flag: "Ⓛ"),
        CurrencyItem(code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭"),
        CurrencyItem(code: "KPW", name: "North Korean Won", flag: "🇰🇵"),
        CurrencyItem(code: "TITS", name: "TITS", flag: "ⓉⒾ"),
        CurrencyItem(code: "USDY", name: "Ondo USDY", flag: "💵"),
        CurrencyItem(code: "USDX", name: "USDX", flag: "💵"),
        CurrencyItem(code: "EDU", name: "EDU", flag: "ⒺⒹ"),
        CurrencyItem(code: "MEDIA", name: "MEDIA", flag: "ⓂⒺ"),
        CurrencyItem(code: "KEEP", name: "KEEP", flag: "ⓀⒺ"),
        CurrencyItem(code: "CAD", name: "Canadian Dollar", flag: "🇨🇦"),
        CurrencyItem(code: "AUDD", name: "AUDD", flag: "ⒶⓊ"),
        CurrencyItem(code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺"),
        CurrencyItem(code: "USD1", name: "USD1", flag: "💵"),
        CurrencyItem(code: "IMP", name: "Isle of Man Pound", flag: "🇮🇲"),
        CurrencyItem(code: "USD0", name: "Usual USD", flag: "💵"),
        CurrencyItem(code: "GIP", name: "Gibraltar Pound", flag: "🇬🇮"),
        CurrencyItem(code: "IMU", name: "IMU", flag: "ⒾⓂ"),
        CurrencyItem(code: "BEAM", name: "BEAM", flag: "ⒷⒺ"),
        CurrencyItem(code: "CAP", name: "CAP", flag: "ⒸⒶ"),
        CurrencyItem(code: "CAR", name: "CAR", flag: "ⒸⒶ"),
        CurrencyItem(code: "IMX", name: "IMX", flag: "ⒾⓂ"),
        CurrencyItem(code: "CAT", name: "CAT", flag: "ⒸⒶ"),
        CurrencyItem(code: "RNBW", name: "RNBW", flag: "ⓇⓃ"),
        CurrencyItem(code: "USDE", name: "Ethena USDe", flag: "💵"),
        CurrencyItem(code: "BARSIK", name: "BARSIK", flag: "ⒷⒶ"),
        CurrencyItem(code: "TREE", name: "TREE", flag: "ⓉⓇ"),
        CurrencyItem(code: "USDD", name: "USDD", flag: "💵"),
        CurrencyItem(code: "USDC", name: "USD Coin", flag: "💵"),
        CurrencyItem(code: "USDB", name: "USDB", flag: "💵"),
        CurrencyItem(code: "KRD", name: "KRD", flag: "ⓀⓇ"),
        CurrencyItem(code: "USDA", name: "Angle USDA", flag: "💵"),
        CurrencyItem(code: "XMON", name: "XMON", flag: "ⓍⓂ"),
        CurrencyItem(code: "RETH", name: "Rocket Pool ETH", flag: "Ξ"),
        CurrencyItem(code: "INJ", name: "INJ", flag: "ⒾⓃ"),
        CurrencyItem(code: "KRL", name: "KRL", flag: "ⓀⓇ"),
        CurrencyItem(code: "VGX", name: "VGX", flag: "ⓋⒼ"),
        CurrencyItem(code: "CHEX", name: "CHEX", flag: "ⒸⒽ"),
        CurrencyItem(code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻"),
        CurrencyItem(code: "TRIBE", name: "TRIBE", flag: "ⓉⓇ"),
        CurrencyItem(code: "INR", name: "Indian Rupee", flag: "🇮🇳"),
        CurrencyItem(code: "DIEM", name: "DIEM", flag: "ⒹⒾ"),
        CurrencyItem(code: "INV", name: "INV", flag: "ⒾⓃ"),
        CurrencyItem(code: "KRW", name: "South Korean Won", flag: "🇰🇷"),
        CurrencyItem(code: "INX", name: "INX", flag: "ⒾⓃ"),
        CurrencyItem(code: "GAME", name: "GAME", flag: "ⒼⒶ"),
        CurrencyItem(code: "KERNEL", name: "KERNEL", flag: "ⓀⒺ"),
        CurrencyItem(code: "STSOL", name: "STSOL", flag: "ⓈⓉ"),
        CurrencyItem(code: "MWC", name: "MWC", flag: "ⓂⓌ"),
        CurrencyItem(code: "XLM", name: "XLM", flag: "ⓍⓁ"),
        CurrencyItem(code: "DORA", name: "DORA", flag: "ⒹⓄ"),
        CurrencyItem(code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼"),
        CurrencyItem(code: "EIGEN", name: "EIGEN", flag: "ⒺⒾ"),
        CurrencyItem(code: "SUPER", name: "SUPER", flag: "ⓈⓊ"),
        CurrencyItem(code: "KSM", name: "KSM", flag: "ⓀⓈ"),
        CurrencyItem(code: "BSC-USD", name: "BSC-USD", flag: "ⒷⓈ"),
        CurrencyItem(code: "RNDR", name: "RNDR", flag: "ⓇⓃ"),
        CurrencyItem(code: "ANIME", name: "ANIME", flag: "ⒶⓃ"),
        CurrencyItem(code: "GALA", name: "GALA", flag: "ⒼⒶ"),
        CurrencyItem(code: "EGP", name: "Egyptian Pound", flag: "🇪🇬"),
        CurrencyItem(code: "RAD", name: "RAD", flag: "ⓇⒶ"),
        CurrencyItem(code: "BLEND", name: "BLEND", flag: "ⒷⓁ"),
        CurrencyItem(code: "MOVE", name: "MOVE", flag: "ⓂⓄ"),
        CurrencyItem(code: "KTA", name: "KTA", flag: "ⓀⓉ"),
        CurrencyItem(code: "MXC", name: "MXC", flag: "ⓂⓍ"),
        CurrencyItem(code: "TEL", name: "TEL", flag: "ⓉⒺ"),
        CurrencyItem(code: "MOVR", name: "MOVR", flag: "ⓂⓄ"),
        CurrencyItem(code: "RAI", name: "RAI", flag: "ⓇⒶ"),
        CurrencyItem(code: "XMR", name: "XMR", flag: "ⓍⓂ"),
        CurrencyItem(code: "MXN", name: "Mexican Peso", flag: "🇲🇽"),
        CurrencyItem(code: "TET", name: "TET", flag: "ⓉⒺ"),
        CurrencyItem(code: "TRIP", name: "TRIP", flag: "ⓉⓇ"),
        CurrencyItem(code: "MCOIN", name: "MCOIN", flag: "ⓂⒸ"),
        CurrencyItem(code: "CDF", name: "Congolese Franc", flag: "🇨🇩"),
        CurrencyItem(code: "GLM", name: "GLM", flag: "ⒼⓁ"),
        CurrencyItem(code: "RAY", name: "RAY", flag: "ⓇⒶ"),
        CurrencyItem(code: "BTC.B", name: "Bitcoin (Avalanche)", flag: "₿"),
        CurrencyItem(code: "FIGHT", name: "FIGHT", flag: "ⒻⒾ"),
        CurrencyItem(code: "ZORA", name: "ZORA", flag: "ⓏⓄ"),
        CurrencyItem(code: "FDUSD", name: "First Digital USD", flag: "💵"),
        CurrencyItem(code: "ZRO", name: "ZRO", flag: "ⓏⓇ"),
        CurrencyItem(code: "BILL", name: "BILL", flag: "ⒷⒾ"),
        CurrencyItem(code: "SAROS", name: "SAROS", flag: "ⓈⒶ"),
        CurrencyItem(code: "KUB", name: "KUB", flag: "ⓀⓊ"),
        CurrencyItem(code: "SSOL", name: "SSOL", flag: "ⓈⓈ"),
        CurrencyItem(code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶"),
        CurrencyItem(code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲"),
        CurrencyItem(code: "RBN", name: "RBN", flag: "ⓇⒷ"),
        CurrencyItem(code: "ZRX", name: "ZRX", flag: "ⓏⓇ"),
        CurrencyItem(code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾"),
        CurrencyItem(code: "CEL", name: "CEL", flag: "ⒸⒺ"),
        CurrencyItem(code: "SERAPH", name: "SERAPH", flag: "ⓈⒺ"),
        CurrencyItem(code: "XOF", name: "West African CFA Franc", flag: "🌍"),
        CurrencyItem(code: "GMT", name: "GMT", flag: "ⒼⓂ"),
        CurrencyItem(code: "BEER", name: "BEER", flag: "ⒷⒺ"),
        CurrencyItem(code: "SWETH", name: "Swell ETH", flag: "Ξ"),
        CurrencyItem(code: "TRIA", name: "TRIA", flag: "ⓉⓇ"),
        CurrencyItem(code: "CET", name: "CET", flag: "ⒸⒺ"),
        CurrencyItem(code: "GMX", name: "GMX", flag: "ⒼⓂ"),
        CurrencyItem(code: "OMNI", name: "OMNI", flag: "ⓄⓂ"),
        CurrencyItem(code: "GNF", name: "Guinean Franc", flag: "🇬🇳"),
        CurrencyItem(code: "MZN", name: "Mozambican Metical", flag: "🇲🇿"),
        CurrencyItem(code: "ICNT", name: "ICNT", flag: "ⒾⒸ"),
        CurrencyItem(code: "CFG", name: "CFG", flag: "ⒸⒻ"),
        CurrencyItem(code: "IRR", name: "Iranian Rial", flag: "🇮🇷"),
        CurrencyItem(code: "GNO", name: "GNO", flag: "ⒼⓃ"),
        CurrencyItem(code: "GNS", name: "GNS", flag: "ⒼⓃ"),
        CurrencyItem(code: "XPD", name: "XPD", flag: "ⓍⓅ"),
        CurrencyItem(code: "THB", name: "Thai Baht", flag: "🇹🇭"),
        CurrencyItem(code: "XPF", name: "CFP Franc", flag: "🇵🇫"),
        CurrencyItem(code: "VANRY", name: "VANRY", flag: "ⓋⒶ"),
        CurrencyItem(code: "WSTUSR", name: "WSTUSR", flag: "ⓌⓈ"),
        CurrencyItem(code: "BITCOIN", name: "BITCOIN", flag: "ⒷⒾ"),
        CurrencyItem(code: "ABT", name: "ABT", flag: "ⒶⒷ"),
        CurrencyItem(code: "CHIP", name: "CHIP", flag: "ⒸⒽ"),
        CurrencyItem(code: "CFX", name: "CFX", flag: "ⒸⒻ"),
        CurrencyItem(code: "XPL", name: "XPL", flag: "ⓍⓅ"),
        CurrencyItem(code: "CDAI", name: "CDAI", flag: "ⒸⒹ"),
        CurrencyItem(code: "MEGA", name: "MEGA", flag: "ⓂⒺ"),
        CurrencyItem(code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼"),
        CurrencyItem(code: "VELO", name: "VELO", flag: "ⓋⒺ"),
        CurrencyItem(code: "BINK", name: "BINK", flag: "ⒷⒾ"),
        CurrencyItem(code: "THQ", name: "THQ", flag: "ⓉⒽ"),
        CurrencyItem(code: "XPT", name: "XPT", flag: "ⓍⓅ"),
        CurrencyItem(code: "ISK", name: "Icelandic Krona", flag: "🇮🇸"),
        CurrencyItem(code: "ACH", name: "ACH", flag: "ⒶⒸ"),
        CurrencyItem(code: "MINA", name: "MINA", flag: "ⓂⒾ"),
        CurrencyItem(code: "KITE", name: "KITE", flag: "ⓀⒾ"),
        CurrencyItem(code: "TIA", name: "TIA", flag: "ⓉⒾ"),
        CurrencyItem(code: "VTHO", name: "VTHO", flag: "ⓋⓉ"),
        CurrencyItem(code: "DRIFT", name: "DRIFT", flag: "ⒹⓇ"),
        CurrencyItem(code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦"),
        CurrencyItem(code: "RED", name: "RED", flag: "ⓇⒺ"),
        CurrencyItem(code: "ACS", name: "ACS", flag: "ⒶⒸ"),
        CurrencyItem(code: "ACT", name: "ACT", flag: "ⒶⒸ"),
        CurrencyItem(code: "ACX", name: "ACX", flag: "ⒶⒸ"),
        CurrencyItem(code: "REI", name: "REI", flag: "ⓇⒺ"),
        CurrencyItem(code: "REN", name: "REN", flag: "ⓇⒺ"),
        CurrencyItem(code: "ELA", name: "ELA", flag: "ⒺⓁ"),
        CurrencyItem(code: "REP", name: "REP", flag: "ⓇⒺ"),
        CurrencyItem(code: "ADA", name: "ADA", flag: "ⒶⒹ"),
        CurrencyItem(code: "ELF", name: "ELF", flag: "ⒺⓁ"),
        CurrencyItem(code: "REQ", name: "REQ", flag: "ⓇⒺ"),
        CurrencyItem(code: "STORJ", name: "STORJ", flag: "ⓈⓉ"),
        CurrencyItem(code: "VIRTUAL", name: "VIRTUAL", flag: "ⓋⒾ"),
        CurrencyItem(code: "CHF", name: "Swiss Franc", flag: "🇨🇭"),
        CurrencyItem(code: "RARI", name: "RARI", flag: "ⓇⒶ"),
        CurrencyItem(code: "ELG", name: "ELG", flag: "ⒺⓁ"),
        CurrencyItem(code: "ULTIMA", name: "ULTIMA", flag: "ⓊⓁ"),
        CurrencyItem(code: "RARE", name: "RARE", flag: "ⓇⒶ"),
        CurrencyItem(code: "LADYS", name: "LADYS", flag: "ⓁⒶ"),
        CurrencyItem(code: "PAXG", name: "PAXG", flag: "ⓅⒶ"),
        CurrencyItem(code: "PAX", name: "Paxos Standard", flag: "💵"),
        CurrencyItem(code: "REZ", name: "REZ", flag: "ⓇⒺ"),
        CurrencyItem(code: "STBTC", name: "Staked BTC", flag: "₿"),
        CurrencyItem(code: "GPS", name: "GPS", flag: "ⒼⓅ"),
        CurrencyItem(code: "XRD", name: "XRD", flag: "ⓍⓇ"),
        CurrencyItem(code: "CHR", name: "CHR", flag: "ⒸⒽ"),
        CurrencyItem(code: "VND", name: "Vietnamese Dong", flag: "🇻🇳"),
        CurrencyItem(code: "CHZ", name: "CHZ", flag: "ⒸⒽ"),
        CurrencyItem(code: "KYD", name: "Cayman Islands Dollar", flag: "🇰🇾"),
        CurrencyItem(code: "XRP", name: "XRP", flag: "ⓍⓇ"),
        CurrencyItem(code: "JASMY", name: "JASMY", flag: "ⒿⒶ"),
        CurrencyItem(code: "INDEX", name: "INDEX", flag: "ⒾⓃ"),
        CurrencyItem(code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯"),
        CurrencyItem(code: "AED", name: "UAE Dirham", flag: "🇦🇪"),
        CurrencyItem(code: "FIDA", name: "FIDA", flag: "ⒻⒾ"),
        CurrencyItem(code: "H2O", name: "H2O", flag: "Ⓗ"),
        CurrencyItem(code: "OCEAN", name: "OCEAN", flag: "ⓄⒸ"),
        CurrencyItem(code: "QGOLD", name: "QGOLD", flag: "ⓆⒼ"),
        CurrencyItem(code: "BIRB", name: "BIRB", flag: "ⒷⒾ"),
        CurrencyItem(code: "ZWG", name: "Zimbabwe Gold", flag: "🇿🇼"),
        CurrencyItem(code: "ZWL", name: "Zimbabwean Dollar", flag: "🇿🇼"),
        CurrencyItem(code: "PCI", name: "PCI", flag: "ⓅⒸ"),
        CurrencyItem(code: "ENA", name: "ENA", flag: "ⒺⓃ"),
        CurrencyItem(code: "RGT", name: "RGT", flag: "ⓇⒼ"),
        CurrencyItem(code: "ENJ", name: "ENJ", flag: "ⒺⓃ"),
        CurrencyItem(code: "TKX", name: "TKX", flag: "ⓉⓀ"),
        CurrencyItem(code: "YAYSTONE", name: "YAYSTONE", flag: "ⓎⒶ"),
        CurrencyItem(code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿"),
        CurrencyItem(code: "YFII", name: "YFII", flag: "ⓎⒻ"),
        CurrencyItem(code: "TOWNS", name: "TOWNS", flag: "ⓉⓄ"),
        CurrencyItem(code: "DIMO", name: "DIMO", flag: "ⒹⒾ"),
        CurrencyItem(code: "GRT", name: "GRT", flag: "ⒼⓇ"),
        CurrencyItem(code: "HBTC", name: "HBTC", flag: "ⒽⒷ"),
        CurrencyItem(code: "RECALL", name: "RECALL", flag: "ⓇⒺ"),
        CurrencyItem(code: "INSURANCE", name: "INSURANCE", flag: "ⒾⓃ"),
        CurrencyItem(code: "AFN", name: "Afghan Afghani", flag: "🇦🇫"),
        CurrencyItem(code: "TFUEL", name: "TFUEL", flag: "ⓉⒻ"),
        CurrencyItem(code: "ENS", name: "ENS", flag: "ⒺⓃ"),
        CurrencyItem(code: "KAIA", name: "KAIA", flag: "ⓀⒶ"),
        CurrencyItem(code: "DEGEN", name: "DEGEN", flag: "ⒹⒺ"),
        CurrencyItem(code: "JITOSOL", name: "JITOSOL", flag: "ⒿⒾ"),
        CurrencyItem(code: "LIGHTER", name: "LIGHTER", flag: "ⓁⒾ"),
        CurrencyItem(code: "CKB", name: "CKB", flag: "ⒸⓀ"),
        CurrencyItem(code: "LUNC", name: "LUNC", flag: "ⓁⓊ"),
        CurrencyItem(code: "XTZ", name: "XTZ", flag: "ⓍⓉ"),
        CurrencyItem(code: "KAIO", name: "KAIO", flag: "ⓀⒶ"),
        CurrencyItem(code: "LUNA", name: "LUNA", flag: "ⓁⓊ"),
        CurrencyItem(code: "AURORA", name: "AURORA", flag: "ⒶⓊ"),
        CurrencyItem(code: "AGI", name: "AGI", flag: "ⒶⒼ"),
        CurrencyItem(code: "EOS", name: "EOS", flag: "ⒺⓄ"),
        CurrencyItem(code: "GST", name: "GST", flag: "ⒼⓈ"),
        CurrencyItem(code: "FORT", name: "FORT", flag: "ⒻⓄ"),
        CurrencyItem(code: "RIF", name: "RIF", flag: "ⓇⒾ"),
        CurrencyItem(code: "NAD", name: "Namibian Dollar", flag: "🇳🇦"),
        CurrencyItem(code: "FRXETH", name: "Frax ETH", flag: "Ξ"),
        CurrencyItem(code: "DEEP", name: "DEEP", flag: "ⒹⒺ"),
        CurrencyItem(code: "SLERF", name: "SLERF", flag: "ⓈⓁ"),
        CurrencyItem(code: "GTC", name: "GTC", flag: "ⒼⓉ"),
        CurrencyItem(code: "PEN", name: "Peruvian Sol", flag: "🇵🇪"),
        CurrencyItem(code: "SOLO", name: "SOLO", flag: "ⓈⓄ"),
        CurrencyItem(code: "TMT", name: "Turkmenistani Manat", flag: "🇹🇲"),
        CurrencyItem(code: "CLF", name: "CLF", flag: "ⒸⓁ"),
        CurrencyItem(code: "TOSHI", name: "TOSHI", flag: "ⓉⓄ"),
        CurrencyItem(code: "HOME", name: "HOME", flag: "ⒽⓄ"),
        CurrencyItem(code: "EUROC", name: "EUROC", flag: "ⒺⓊ"),
        CurrencyItem(code: "SUNDOG", name: "SUNDOG", flag: "ⓈⓊ"),
        CurrencyItem(code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹"),
        CurrencyItem(code: "CLP", name: "Chilean Peso", flag: "🇨🇱"),
        CurrencyItem(code: "CPOOL", name: "CPOOL", flag: "ⒸⓅ"),
        CurrencyItem(code: "TND", name: "Tunisian Dinar", flag: "🇹🇳"),
        CurrencyItem(code: "CLV", name: "CLV", flag: "ⒸⓁ"),
        CurrencyItem(code: "XVS", name: "XVS", flag: "ⓍⓋ"),
        CurrencyItem(code: "MEME", name: "MEME", flag: "ⓂⒺ"),
        CurrencyItem(code: "ELSA", name: "ELSA", flag: "ⒺⓁ"),
        CurrencyItem(code: "W3S", name: "W3S", flag: "Ⓦ"),
        CurrencyItem(code: "LYXE", name: "LYXE", flag: "ⓁⓎ"),
        CurrencyItem(code: "AIC", name: "AIC", flag: "ⒶⒾ"),
        CurrencyItem(code: "BREV", name: "BREV", flag: "ⒷⓇ"),
        CurrencyItem(code: "SFUND", name: "SFUND", flag: "ⓈⒻ"),
        CurrencyItem(code: "TON", name: "TON", flag: "ⓉⓄ"),
        CurrencyItem(code: "TOP", name: "TOP", flag: "ⓉⓄ"),
        CurrencyItem(code: "ERA", name: "ERA", flag: "ⒺⓇ"),
        CurrencyItem(code: "PGK", name: "Papua New Guinean Kina", flag: "🇵🇬"),
        CurrencyItem(code: "ASTER", name: "ASTER", flag: "ⒶⓈ"),
        CurrencyItem(code: "PNUT", name: "PNUT", flag: "ⓅⓃ"),
        CurrencyItem(code: "RAVE", name: "RAVE", flag: "ⓇⒶ"),
        CurrencyItem(code: "GYEN", name: "GYEN", flag: "ⒼⓎ"),
        CurrencyItem(code: "CNH", name: "Chinese Yuan (Offshore)", flag: "🇨🇳"),
        CurrencyItem(code: "NCT", name: "NCT", flag: "ⓃⒸ"),
        CurrencyItem(code: "WLUNA", name: "WLUNA", flag: "ⓌⓁ"),
        CurrencyItem(code: "ERN", name: "ERN", flag: "ⒺⓇ"),
        CurrencyItem(code: "VENOM", name: "VENOM", flag: "ⓋⒺ"),
        CurrencyItem(code: "VOXEL", name: "VOXEL", flag: "ⓋⓄ"),
        CurrencyItem(code: "PHA", name: "PHA", flag: "ⓅⒽ"),
        CurrencyItem(code: "RLC", name: "RLC", flag: "ⓇⓁ"),
        CurrencyItem(code: "RLB", name: "RLB", flag: "ⓇⓁ"),
        CurrencyItem(code: "MAGA", name: "MAGA", flag: "ⓂⒶ"),
        CurrencyItem(code: "CNY", name: "Chinese Yuan", flag: "🇨🇳"),
        CurrencyItem(code: "RLS", name: "RLS", flag: "ⓇⓁ"),
        CurrencyItem(code: "IBERA", name: "IBERA", flag: "ⒾⒷ"),
        CurrencyItem(code: "PHP", name: "Philippine Peso", flag: "🇵🇭"),
        CurrencyItem(code: "RLY", name: "RLY", flag: "ⓇⓁ"),
        CurrencyItem(code: "ESP", name: "ESP", flag: "ⒺⓈ"),
        CurrencyItem(code: "COQ", name: "COQ", flag: "ⒸⓄ"),
        CurrencyItem(code: "COP", name: "Colombian Peso", flag: "🇨🇴"),
        CurrencyItem(code: "HOPR", name: "HOPR", flag: "ⒽⓄ"),
        CurrencyItem(code: "AKT", name: "AKT", flag: "ⒶⓀ"),
        CurrencyItem(code: "COW", name: "COW", flag: "ⒸⓄ"),
        CurrencyItem(code: "GLMR", name: "GLMR", flag: "ⒼⓁ"),
        CurrencyItem(code: "ORAI", name: "ORAI", flag: "ⓄⓇ"),
        CurrencyItem(code: "XYO", name: "XYO", flag: "ⓍⓎ"),
        CurrencyItem(code: "PROVE", name: "PROVE", flag: "ⓅⓇ"),
        CurrencyItem(code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹"),
        CurrencyItem(code: "GXC", name: "GXC", flag: "ⒼⓍ"),
        CurrencyItem(code: "NEI", name: "NEI", flag: "ⓃⒺ"),
        CurrencyItem(code: "ETC", name: "ETC", flag: "ⒺⓉ"),
        CurrencyItem(code: "PIP", name: "PIP", flag: "ⓅⒾ"),
        CurrencyItem(code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺"),
        CurrencyItem(code: "LAK", name: "Laotian Kip", flag: "🇱🇦"),
        CurrencyItem(code: "ETH", name: "Ethereum", flag: "Ξ"),
        CurrencyItem(code: "NEO", name: "NEO", flag: "ⓃⒺ"),
        CurrencyItem(code: "KLAY", name: "KLAY", flag: "ⓀⓁ"),
        CurrencyItem(code: "STEAKEURCV", name: "STEAKEURCV", flag: "ⓈⓉ"),
        CurrencyItem(code: "NEX", name: "NEX", flag: "ⓃⒺ"),
        CurrencyItem(code: "ALL", name: "Albanian Lek", flag: "🇦🇱"),
        CurrencyItem(code: "MAVIA", name: "MAVIA", flag: "ⓂⒶ"),
        CurrencyItem(code: "HIGH", name: "HIGH", flag: "ⒽⒾ"),
        CurrencyItem(code: "USELESS", name: "USELESS", flag: "ⓊⓈ"),
        CurrencyItem(code: "TRB", name: "TRB", flag: "ⓉⓇ"),
        CurrencyItem(code: "CLANKER", name: "CLANKER", flag: "ⒸⓁ"),
        CurrencyItem(code: "ALT", name: "ALT", flag: "ⒶⓁ"),
        CurrencyItem(code: "ORDI", name: "ORDI", flag: "ⓄⓇ"),
        CurrencyItem(code: "GYD", name: "Guyanaese Dollar", flag: "🇬🇾"),
        CurrencyItem(code: "OSETH", name: "StakeWise ETH", flag: "Ξ"),
        CurrencyItem(code: "TRU", name: "TRU", flag: "ⓉⓇ"),
        CurrencyItem(code: "VVV", name: "VVV", flag: "ⓋⓋ"),
        CurrencyItem(code: "WBNB", name: "WBNB", flag: "ⓌⒷ"),
        CurrencyItem(code: "AMD", name: "Armenian Dram", flag: "🇦🇲"),
        CurrencyItem(code: "GRASS", name: "GRASS", flag: "ⒼⓇ"),
        CurrencyItem(code: "ETHDYDX", name: "ETHDYDX", flag: "ⒺⓉ"),
        CurrencyItem(code: "TRY", name: "Turkish Lira", flag: "🇹🇷"),
        CurrencyItem(code: "LBP", name: "Lebanese Pound", flag: "🇱🇧"),
        CurrencyItem(code: "TRX", name: "TRX", flag: "ⓉⓇ"),
        CurrencyItem(code: "SIGN", name: "SIGN", flag: "ⓈⒾ"),
        CurrencyItem(code: "UBTC", name: "Universal BTC", flag: "₿"),
        CurrencyItem(code: "EUL", name: "EUL", flag: "ⒺⓊ"),
        CurrencyItem(code: "NFT", name: "NFT", flag: "ⓃⒻ"),
        CurrencyItem(code: "EDGE", name: "EDGE", flag: "ⒺⒹ"),
        CurrencyItem(code: "EUR", name: "Euro", flag: "🇪🇺"),
        CurrencyItem(code: "AMP", name: "AMP", flag: "ⒶⓂ"),
        CurrencyItem(code: "MEOW", name: "MEOW", flag: "ⓂⒺ"),
        CurrencyItem(code: "ORCA", name: "ORCA", flag: "ⓄⓇ"),
        CurrencyItem(code: "USTC", name: "TerraClassicUSD", flag: "💵"),
        CurrencyItem(code: "BERA", name: "BERA", flag: "ⒷⒺ"),
        CurrencyItem(code: "RON", name: "Romanian Leu", flag: "🇷🇴"),
        CurrencyItem(code: "NGN", name: "Nigerian Naira", flag: "🇳🇬"),
        CurrencyItem(code: "TST", name: "TST", flag: "ⓉⓈ"),
        CurrencyItem(code: "CRC", name: "Costa Rican Colon", flag: "🇨🇷"),
        CurrencyItem(code: "GWEI", name: "GWEI", flag: "ⒼⓌ"),
        CurrencyItem(code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰"),
        CurrencyItem(code: "VANA", name: "VANA", flag: "ⓋⒶ"),
        CurrencyItem(code: "LUSD", name: "Liquity USD", flag: "💵"),
        CurrencyItem(code: "ANG", name: "Netherlands Antillean Guilder", flag: "🇨🇼"),
        CurrencyItem(code: "SPELL", name: "SPELL", flag: "ⓈⓅ"),
        CurrencyItem(code: "LCX", name: "LCX", flag: "ⓁⒸ"),
        CurrencyItem(code: "CRO", name: "CRO", flag: "ⒸⓇ"),
        CurrencyItem(code: "PLA", name: "PLA", flag: "ⓅⓁ"),
        CurrencyItem(code: "TTD", name: "Trinidad and Tobago Dollar", flag: "🇹🇹"),
        CurrencyItem(code: "SFRXETH", name: "Staked Frax ETH", flag: "Ξ"),
        CurrencyItem(code: "CRV", name: "CRV", flag: "ⒸⓇ"),
        CurrencyItem(code: "MNDE", name: "MNDE", flag: "ⓂⓃ"),
        CurrencyItem(code: "ANT", name: "ANT", flag: "ⒶⓃ"),
        CurrencyItem(code: "BAKE", name: "BAKE", flag: "ⒷⒶ"),
        CurrencyItem(code: "RPL", name: "RPL", flag: "ⓇⓅ"),
        CurrencyItem(code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴"),
        CurrencyItem(code: "PLN", name: "Polish Zloty", flag: "🇵🇱"),
        CurrencyItem(code: "AZERO", name: "AZERO", flag: "ⒶⓏ"),
        CurrencyItem(code: "LDO", name: "LDO", flag: "ⓁⒹ"),
        CurrencyItem(code: "MAGIC", name: "MAGIC", flag: "ⓂⒶ"),
        CurrencyItem(code: "ALICE", name: "ALICE", flag: "ⒶⓁ"),
        CurrencyItem(code: "CORECHAIN", name: "CORECHAIN", flag: "ⒸⓄ"),
        CurrencyItem(code: "PLU", name: "PLU", flag: "ⓅⓁ"),
        CurrencyItem(code: "SEAM", name: "SEAM", flag: "ⓈⒺ"),
        CurrencyItem(code: "AMAPT", name: "AMAPT", flag: "ⒶⓂ"),
        CurrencyItem(code: "CTB", name: "CTB", flag: "ⒸⓉ"),
        CurrencyItem(code: "ZEREBRO", name: "ZEREBRO", flag: "ⓏⒺ"),
        CurrencyItem(code: "CTC", name: "CTC", flag: "ⒸⓉ"),
        CurrencyItem(code: "NIO", name: "Nicaraguan Cordoba", flag: "🇳🇮"),
        CurrencyItem(code: "APE", name: "APE", flag: "ⒶⓅ"),
        CurrencyItem(code: "LEO", name: "LEO", flag: "ⓁⒺ"),
        CurrencyItem(code: "MCO2", name: "MCO2", flag: "ⓂⒸ"),
        CurrencyItem(code: "00", name: "00", flag: "💵"),
        CurrencyItem(code: "CTR", name: "CTR", flag: "ⒸⓉ"),
        CurrencyItem(code: "MATIC", name: "MATIC", flag: "ⓂⒶ"),
        CurrencyItem(code: "APR", name: "APR", flag: "ⒶⓅ"),
        CurrencyItem(code: "APT", name: "APT", flag: "ⒶⓅ"),
        CurrencyItem(code: "APU", name: "APU", flag: "ⒶⓅ"),
        CurrencyItem(code: "CTX", name: "CTX", flag: "ⒸⓉ"),
        CurrencyItem(code: "PNG", name: "PNG", flag: "ⓅⓃ"),
        CurrencyItem(code: "TVK", name: "TVK", flag: "ⓉⓋ"),
        CurrencyItem(code: "USYC", name: "USYC", flag: "ⓊⓈ"),
        CurrencyItem(code: "CUC", name: "Cuban Convertible Peso", flag: "🇨🇺"),
        CurrencyItem(code: "MAMO", name: "MAMO", flag: "ⓂⒶ"),
        CurrencyItem(code: "PYTH", name: "PYTH", flag: "ⓅⓎ"),
        CurrencyItem(code: "AI16Z", name: "AI16Z", flag: "ⒶⒾ"),
        CurrencyItem(code: "CUP", name: "Cuban Peso", flag: "🇨🇺"),
        CurrencyItem(code: "TWD", name: "New Taiwan Dollar", flag: "🇹🇼"),
        CurrencyItem(code: "IRYS", name: "IRYS", flag: "ⒾⓇ"),
        CurrencyItem(code: "META", name: "META", flag: "ⓂⒺ"),
        CurrencyItem(code: "RSD", name: "Serbian Dinar", flag: "🇷🇸"),
        CurrencyItem(code: "FRAX", name: "Frax", flag: "💵"),
        CurrencyItem(code: "RSC", name: "RSC", flag: "ⓇⓈ"),
        CurrencyItem(code: "VRSC", name: "VRSC", flag: "ⓋⓇ"),
        CurrencyItem(code: "WBETH", name: "Wrapped Beacon ETH", flag: "Ξ"),
        CurrencyItem(code: "METH", name: "Mantle ETH", flag: "Ξ"),
        CurrencyItem(code: "BAND", name: "BAND", flag: "ⒷⒶ"),
        CurrencyItem(code: "POL", name: "POL", flag: "ⓅⓄ"),
        CurrencyItem(code: "ASTR", name: "ASTR", flag: "ⒶⓈ"),
        CurrencyItem(code: "NKN", name: "NKN", flag: "ⓃⓀ"),
        CurrencyItem(code: "RSR", name: "RSR", flag: "ⓇⓈ"),
        CurrencyItem(code: "TWT", name: "TWT", flag: "ⓉⓌ"),
        CurrencyItem(code: "PARTI", name: "PARTI", flag: "ⓅⒶ"),
        CurrencyItem(code: "ARB", name: "ARB", flag: "ⒶⓇ"),
        CurrencyItem(code: "CVC", name: "CVC", flag: "ⒸⓋ"),
        CurrencyItem(code: "ARC", name: "ARC", flag: "ⒶⓇ"),
        CurrencyItem(code: "VARA", name: "VARA", flag: "ⓋⒶ"),
        CurrencyItem(code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻"),
        CurrencyItem(code: "SUSDS", name: "Savings USDS", flag: "💵"),
        CurrencyItem(code: "ARK", name: "ARK", flag: "ⒶⓇ"),
        CurrencyItem(code: "LOKA", name: "LOKA", flag: "ⓁⓄ"),
        CurrencyItem(code: "BTSE", name: "BTSE", flag: "ⒷⓉ"),
        CurrencyItem(code: "CHEEMS", name: "CHEEMS", flag: "ⒸⒽ"),
        CurrencyItem(code: "ARS", name: "Argentine Peso", flag: "🇦🇷"),
        CurrencyItem(code: "CVX", name: "CVX", flag: "ⒸⓋ"),
        CurrencyItem(code: "LBTC", name: "Lombard BTC", flag: "₿"),
        CurrencyItem(code: "ARX", name: "ARX", flag: "ⒶⓇ"),
        CurrencyItem(code: "MPLX", name: "MPLX", flag: "ⓂⓅ"),
        CurrencyItem(code: "SUSHI", name: "SUSHI", flag: "ⓈⓊ"),
        CurrencyItem(code: "PUMP", name: "PUMP", flag: "ⓅⓊ"),
        CurrencyItem(code: "ABTC", name: "aBTC", flag: "₿"),
        CurrencyItem(code: "MANTLE", name: "MANTLE", flag: "ⓂⒶ"),
        CurrencyItem(code: "WBTC", name: "Wrapped Bitcoin", flag: "₿"),
        CurrencyItem(code: "ASM", name: "ASM", flag: "ⒶⓈ"),
        CurrencyItem(code: "RUB", name: "Russian Ruble", flag: "🇷🇺"),
        CurrencyItem(code: "AST", name: "AST", flag: "ⒶⓈ"),
        CurrencyItem(code: "BNSOL", name: "BNSOL", flag: "ⒷⓃ"),
        CurrencyItem(code: "MANA", name: "MANA", flag: "ⓂⒶ"),
        CurrencyItem(code: "2Z", name: "2Z", flag: "Ⓩ"),
        CurrencyItem(code: "CSPR", name: "CSPR", flag: "ⒸⓈ"),
        CurrencyItem(code: "AGENTFUN", name: "AGENTFUN", flag: "ⒶⒼ"),
        CurrencyItem(code: "ATA", name: "ATA", flag: "ⒶⓉ"),
        CurrencyItem(code: "NMR", name: "NMR", flag: "ⓃⓂ"),
        CurrencyItem(code: "STAU", name: "STAU", flag: "ⓈⓉ"),
        CurrencyItem(code: "JEP", name: "Jersey Pound", flag: "🇯🇪"),
        CurrencyItem(code: "NMT", name: "NMT", flag: "ⓃⓂ"),
        CurrencyItem(code: "ATH", name: "ATH", flag: "ⒶⓉ"),
        CurrencyItem(code: "LIT", name: "LIT", flag: "ⓁⒾ"),
        CurrencyItem(code: "TNSR", name: "TNSR", flag: "ⓉⓃ"),
        CurrencyItem(code: "POLYX", name: "POLYX", flag: "ⓅⓄ"),
        CurrencyItem(code: "DESO", name: "DESO", flag: "ⒹⒺ"),
        CurrencyItem(code: "LOOM", name: "LOOM", flag: "ⓁⓄ"),
        CurrencyItem(code: "PRL", name: "PRL", flag: "ⓅⓇ"),
        CurrencyItem(code: "RVN", name: "RVN", flag: "ⓇⓋ"),
        CurrencyItem(code: "PRO", name: "PRO", flag: "ⓅⓇ"),
        CurrencyItem(code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿"),
        CurrencyItem(code: "PRQ", name: "PRQ", flag: "ⓅⓇ"),
        CurrencyItem(code: "ONDO", name: "ONDO", flag: "ⓄⓃ"),
        CurrencyItem(code: "AUD", name: "Australian Dollar", flag: "🇦🇺"),
        CurrencyItem(code: "USDT0", name: "USDT0", flag: "💵"),
        CurrencyItem(code: "BUIDL", name: "BUIDL", flag: "ⒷⓊ"),
        CurrencyItem(code: "ONED", name: "ONED", flag: "ⓄⓃ"),
        CurrencyItem(code: "MONKEYS", name: "MONKEYS", flag: "ⓂⓄ"),
        CurrencyItem(code: "RWF", name: "Rwandan Franc", flag: "🇷🇼"),
        CurrencyItem(code: "KAVA", name: "KAVA", flag: "ⓀⒶ"),
        CurrencyItem(code: "AZTEC", name: "AZTEC", flag: "ⒶⓏ"),
        CurrencyItem(code: "NOK", name: "Norwegian Krone", flag: "🇳🇴"),
        CurrencyItem(code: "BNKR", name: "BNKR", flag: "ⒷⓃ"),
        CurrencyItem(code: "NOM", name: "NOM", flag: "ⓃⓄ"),
        CurrencyItem(code: "BARD", name: "BARD", flag: "ⒷⒶ"),
        CurrencyItem(code: "STRAX", name: "STRAX", flag: "ⓈⓉ"),
        CurrencyItem(code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰"),
        CurrencyItem(code: "NOT", name: "NOT", flag: "ⓃⓄ"),
        CurrencyItem(code: "NOS", name: "NOS", flag: "ⓃⓄ"),
        CurrencyItem(code: "CZK", name: "Czech Koruna", flag: "🇨🇿"),
        CurrencyItem(code: "AVT", name: "AVT", flag: "ⒶⓋ"),
        CurrencyItem(code: "NPC", name: "NPC", flag: "ⓃⓅ"),
        CurrencyItem(code: "EURC", name: "EURC", flag: "ⒺⓊ"),
        CurrencyItem(code: "WAL", name: "WAL", flag: "ⓌⒶ"),
        CurrencyItem(code: "YER", name: "Yemeni Rial", flag: "🇾🇪"),
        CurrencyItem(code: "LSETH", name: "Liquid Staked ETH", flag: "Ξ"),
        CurrencyItem(code: "SUSDE", name: "Staked USDe", flag: "💵"),
        CurrencyItem(code: "AWE", name: "AWE", flag: "ⒶⓌ"),
        CurrencyItem(code: "MASK", name: "MASK", flag: "ⓂⒶ"),
        CurrencyItem(code: "AWG", name: "Aruban Florin", flag: "🇦🇼"),
        CurrencyItem(code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵"),
        CurrencyItem(code: "ZAMA", name: "ZAMA", flag: "ⓏⒶ"),
        CurrencyItem(code: "PRIME", name: "PRIME", flag: "ⓅⓇ"),
        CurrencyItem(code: "YFI", name: "YFI", flag: "ⓎⒻ"),
        CurrencyItem(code: "MOODENG", name: "MOODENG", flag: "ⓂⓄ"),
        CurrencyItem(code: "CWBTC", name: "Compound WBTC", flag: "₿"),
        CurrencyItem(code: "KEYCAT", name: "KEYCAT", flag: "ⓀⒺ"),
        CurrencyItem(code: "POPCAT", name: "POPCAT", flag: "ⓅⓄ"),
        CurrencyItem(code: "WBT", name: "WBT", flag: "ⓌⒷ"),
        CurrencyItem(code: "LQTY", name: "LQTY", flag: "ⓁⓆ"),
        CurrencyItem(code: "MEZO", name: "MEZO", flag: "ⓂⒺ"),
        CurrencyItem(code: "OLAS", name: "OLAS", flag: "ⓄⓁ"),
        CurrencyItem(code: "ALUSD", name: "Alchemix USD", flag: "💵"),
        CurrencyItem(code: "FAI", name: "FAI", flag: "ⒻⒶ"),
        CurrencyItem(code: "PIXEL", name: "PIXEL", flag: "ⓅⒾ"),
        CurrencyItem(code: "ZETA", name: "ZETA", flag: "ⓏⒺ"),
        CurrencyItem(code: "AXL", name: "AXL", flag: "ⒶⓍ"),
        CurrencyItem(code: "BILLY", name: "BILLY", flag: "ⒷⒾ"),
        CurrencyItem(code: "CHEEL", name: "CHEEL", flag: "ⒸⒽ"),
        CurrencyItem(code: "PIRATE", name: "PIRATE", flag: "ⓅⒾ"),
        CurrencyItem(code: "YGG", name: "YGG", flag: "ⓎⒼ"),
        CurrencyItem(code: "BOBBOB", name: "BOBBOB", flag: "ⒷⓄ"),
        CurrencyItem(code: "FARTCOIN", name: "FARTCOIN", flag: "ⒻⒶ"),
        CurrencyItem(code: "CLBTC", name: "cl BTC", flag: "₿"),
        CurrencyItem(code: "AXS", name: "AXS", flag: "ⒶⓍ"),
        CurrencyItem(code: "SYRUP", name: "SYRUP", flag: "ⓈⓎ"),
        CurrencyItem(code: "HONEY", name: "HONEY", flag: "ⒽⓄ"),
        CurrencyItem(code: "XSOLVBTC", name: "xSolvBTC", flag: "₿"),
        CurrencyItem(code: "0X0", name: "0X0", flag: "Ⓧ"),
        CurrencyItem(code: "WCT", name: "WCT", flag: "ⓌⒸ"),
        CurrencyItem(code: "COMP", name: "COMP", flag: "ⒸⓄ"),
        CurrencyItem(code: "HFT", name: "HFT", flag: "ⒽⒻ"),
        CurrencyItem(code: "WAMPL", name: "WAMPL", flag: "ⓌⒶ"),
        CurrencyItem(code: "UXLINK", name: "UXLINK", flag: "ⓊⓍ"),
        CurrencyItem(code: "CMETH", name: "Mantle Staked ETH", flag: "Ξ"),
        CurrencyItem(code: "RUNE", name: "RUNE", flag: "ⓇⓊ"),
        CurrencyItem(code: "PURR", name: "PURR", flag: "ⓅⓊ"),
        CurrencyItem(code: "ZEUS", name: "ZEUS", flag: "ⓏⒺ"),
        CurrencyItem(code: "PENGU", name: "PENGU", flag: "ⓅⒺ"),
        CurrencyItem(code: "DEXT", name: "DEXT", flag: "ⒹⒺ"),
        CurrencyItem(code: "FORTH", name: "FORTH", flag: "ⒻⓄ"),
        CurrencyItem(code: "GHST", name: "GHST", flag: "ⒼⒽ"),
        CurrencyItem(code: "MATH", name: "MATH", flag: "ⓂⒶ"),
        CurrencyItem(code: "IDEX", name: "IDEX", flag: "ⒾⒹ"),
        CurrencyItem(code: "DEXE", name: "DEXE", flag: "ⒹⒺ"),
        CurrencyItem(code: "VNST", name: "VNST", flag: "ⓋⓃ"),
        CurrencyItem(code: "AVAX", name: "AVAX", flag: "ⒶⓋ"),
        CurrencyItem(code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿"),
        CurrencyItem(code: "AMPL", name: "AMPL", flag: "ⒶⓂ"),
        CurrencyItem(code: "CHECK", name: "CHECK", flag: "ⒸⒽ"),
        CurrencyItem(code: "GOAT", name: "GOAT", flag: "ⒼⓄ"),
        CurrencyItem(code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦"),
        CurrencyItem(code: "BANANA", name: "BANANA", flag: "ⒷⒶ"),
        CurrencyItem(code: "WEN", name: "WEN", flag: "ⓌⒺ"),
        CurrencyItem(code: "WET", name: "WET", flag: "ⓌⒺ"),
        CurrencyItem(code: "LPT", name: "LPT", flag: "ⓁⓅ"),
        CurrencyItem(code: "KAITO", name: "KAITO", flag: "ⓀⒶ"),
        CurrencyItem(code: "EZETH", name: "Renzo ETH", flag: "Ξ"),
        CurrencyItem(code: "GODS", name: "GODS", flag: "ⒼⓄ"),
        CurrencyItem(code: "EDUM", name: "EDUM", flag: "ⒺⒹ"),
        CurrencyItem(code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾"),
        CurrencyItem(code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲"),
        CurrencyItem(code: "XAUT", name: "XAUT", flag: "ⓍⒶ"),
        CurrencyItem(code: "PYR", name: "PYR", flag: "ⓅⓎ"),
        CurrencyItem(code: "BTRST", name: "BTRST", flag: "ⒷⓉ"),
        CurrencyItem(code: "MKUSD", name: "Prisma mkUSD", flag: "💵"),
        CurrencyItem(code: "DAG", name: "DAG", flag: "ⒹⒶ"),
        CurrencyItem(code: "BERASTONE", name: "Berachain stone ETH", flag: "Ξ"),
        CurrencyItem(code: "LQR", name: "LQR", flag: "ⓁⓆ"),
        CurrencyItem(code: "ROBO", name: "ROBO", flag: "ⓇⓄ"),
        CurrencyItem(code: "DAI", name: "Dai", flag: "💵"),
        CurrencyItem(code: "DAO", name: "DAO", flag: "ⒹⒶ"),
        CurrencyItem(code: "AVAIL", name: "AVAIL", flag: "ⒶⓋ"),
        CurrencyItem(code: "DAR", name: "DAR", flag: "ⒹⒶ"),
        CurrencyItem(code: "FET", name: "FET", flag: "ⒻⒺ"),
        CurrencyItem(code: "CBETH", name: "Coinbase Wrapped ETH", flag: "Ξ"),
        CurrencyItem(code: "LRC", name: "LRC", flag: "ⓁⓇ"),
        CurrencyItem(code: "REPV2", name: "REPV2", flag: "ⓇⒺ"),
        CurrencyItem(code: "LRD", name: "Liberian Dollar", flag: "🇱🇷"),
        CurrencyItem(code: "CORE", name: "CORE", flag: "ⒸⓄ"),
        CurrencyItem(code: "DASH", name: "DASH", flag: "ⒹⒶ"),
        CurrencyItem(code: "POKT", name: "POKT", flag: "ⓅⓄ"),
        CurrencyItem(code: "SAGA", name: "SAGA", flag: "ⓈⒶ"),
        CurrencyItem(code: "DBR", name: "DBR", flag: "ⒹⒷ"),
        CurrencyItem(code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴"),
        CurrencyItem(code: "GUSD", name: "Gemini Dollar", flag: "💵"),
        CurrencyItem(code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰"),
        CurrencyItem(code: "JOE", name: "JOE", flag: "ⒿⓄ"),
        CurrencyItem(code: "LSL", name: "Lesotho Loti", flag: "🇱🇸"),
        CurrencyItem(code: "LSK", name: "LSK", flag: "ⓁⓈ"),
        CurrencyItem(code: "PUMPBTC", name: "PumpBTC", flag: "₿"),
        CurrencyItem(code: "SAFE", name: "SAFE", flag: "ⓈⒶ"),
        CurrencyItem(code: "RDOG", name: "RDOG", flag: "ⓇⒹ"),
        CurrencyItem(code: "DCR", name: "DCR", flag: "ⒹⒸ"),
        CurrencyItem(code: "WIF", name: "dogwifhat", flag: "💵"),
        CurrencyItem(code: "DATA", name: "DATA", flag: "ⒹⒶ"),
        CurrencyItem(code: "LTC", name: "Litecoin", flag: "Ⓛ"),
        CurrencyItem(code: "METIS", name: "METIS", flag: "ⓂⒺ"),
        CurrencyItem(code: "SENT", name: "SENT", flag: "ⓈⒺ"),
        CurrencyItem(code: "STETH", name: "Lido Staked ETH", flag: "Ξ"),
        CurrencyItem(code: "NXM", name: "NXM", flag: "ⓃⓍ"),
        CurrencyItem(code: "SAR", name: "Saudi Riyal", flag: "🇸🇦"),
        CurrencyItem(code: "DYDX", name: "DYDX", flag: "ⒹⓎ"),
        CurrencyItem(code: "AGIX", name: "AGIX", flag: "ⒶⒼ"),
        CurrencyItem(code: "MUBI", name: "MUBI", flag: "ⓂⓊ"),
        CurrencyItem(code: "POND", name: "POND", flag: "ⓅⓄ"),
        CurrencyItem(code: "RBNT", name: "RBNT", flag: "ⓇⒷ"),
        CurrencyItem(code: "JPY", name: "Japanese Yen", flag: "🇯🇵"),
        CurrencyItem(code: "UFD", name: "UFD", flag: "ⓊⒻ"),
        CurrencyItem(code: "SBD", name: "Solomon Islands Dollar", flag: "🇸🇧"),
        CurrencyItem(code: "GRIFFAIN", name: "GRIFFAIN", flag: "ⒼⓇ"),
        CurrencyItem(code: "DDX", name: "DDX", flag: "ⒹⒹ"),
        CurrencyItem(code: "LINK", name: "LINK", flag: "ⓁⒾ"),
        CurrencyItem(code: "QTUM", name: "QTUM", flag: "ⓆⓉ"),
        CurrencyItem(code: "WILD", name: "WILD", flag: "ⓌⒾ"),
        CurrencyItem(code: "LMTS", name: "LMTS", flag: "ⓁⓂ"),
        CurrencyItem(code: "POLS", name: "POLS", flag: "ⓅⓄ"),
        CurrencyItem(code: "FIL", name: "FIL", flag: "ⒻⒾ"),
        CurrencyItem(code: "POLY", name: "POLY", flag: "ⓅⓄ"),
        CurrencyItem(code: "EBTC", name: "eBTC", flag: "₿"),
        CurrencyItem(code: "BAL", name: "BAL", flag: "ⒷⒶ"),
        CurrencyItem(code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", flag: "🇧🇦"),
        CurrencyItem(code: "BAN", name: "BAN", flag: "ⒷⒶ"),
        CurrencyItem(code: "FIS", name: "FIS", flag: "ⒻⒾ"),
        CurrencyItem(code: "WMTX", name: "WMTX", flag: "ⓌⓂ"),
        CurrencyItem(code: "BAT", name: "BAT", flag: "ⒷⒶ"),
        CurrencyItem(code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿"),
        CurrencyItem(code: "COTI", name: "COTI", flag: "ⒸⓄ"),
    ]
}
